### ISSUE TITLE
findAll promise warning

### ISSUE THREAD

**Issue by bohrshaw** [sequelize/sequelize-pool#13]
Same as https://github.com/sequelize/sequelize/issues/10628

**Comment by sushantdhiman** [comment]
Need some code that can reproduce this issue, most likely you are not using promises correctly

**Comment by bohrshaw** [comment]
@sushantdhiman 
When executing a line (pseudo code): `model.findAll().then(...).catch(...)`, I got:
```
15-08-2019 16:55:43: (node:31429) Warning: a promise was created in a handler at foo.js:97:37 but was not returned from it, see http://goo.gl/rRqMUw
15-08-2019 16:55:43:     at Function.Promise.attempt.Promise.try (/path/to/node_modules/bluebird/js/release/method.js:29:9)
```

**Comment by sushantdhiman** [comment]
Again this is something not related to Sequelize or pool, you are not using promises correctly. If you can show some code which can reproduce this issue I will take a look

**Comment by bohrshaw** [comment]
Thanks. You are right.
