### ISSUE TITLE
Acquire timeout not respected (seen on MSSQL)

### ISSUE THREAD

**Issue by chrisskalog** [sequelize/sequelize-pool#52]
Hello,

I noticed that on MSSQL, the pool has acquire timeout 60 seconds, but the value is not passed to tedious driver which uses by default 15 secs.
Is this intentional or it is a bug ?

Thanks in advance

**Comment by sushantdhiman** [comment]
This issue should be filed with main repository, as passing settings to driver is not handled in this library.
